### ISSUE TITLE
EventFiringDecorator breaks lots of things e.g. JSExecutor

### ISSUE THREAD

**Issue by ham1** [ham1/frameworkium-lite#51]
```
java.lang.UnsupportedOperationException: null
at org.openqa.selenium.WebElement.getDomAttribute(WebElement.java:131) ~[selenium-api-4.0.0-beta-2.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:52) ~[selenium-support-4.0.0-beta-2.jar:?]
at com.frameworkium.lite.htmlelements.loader.decorator.proxyhandlers.WebElementNamedProxyHandler.invoke(WebElementNamedProxyHandler.java:36) ~[frameworkium-lite-4.1.2.jar:?]
at com.sun.proxy.$Proxy46.getDomAttribute(Unknown Source) ~[?:?]
at org.openqa.selenium.support.ui.Select.<init>(Select.java:54) ~[selenium-support-4.0.0-beta-2.jar:?]
at com.frameworkium.lite.htmlelements.element.Select.getSelect(Select.java:37) ~[frameworkium-lite-4.1.2.jar:?]
at com.frameworkium.lite.htmlelements.element.Select.getOptions(Select.java:45) ~[frameworkium-lite-4.1.2.jar:?]
```

**Comment by ham1** [comment]
Fixed the initial issue, however now we can't execute JS using the WebElements as they are Proxys

```
java.lang.IllegalArgumentException: Argument is of an illegal type: com.sun.proxy.$Proxy35
	at org.openqa.selenium.remote.internal.WebElementToJsonConverter.apply(WebElementToJsonConverter.java:85) ~[selenium-remote-driver-4.0.0-beta-1.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:552) ~[selenium-remote-driver-4.0.0-beta-1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openqa.selenium.support.decorators.WebDriverDecorator.call(WebDriverDecorator.java:228) ~[selenium-support-4.0.0-beta-1.jar:?]
	at org.openqa.selenium.support.decorators.DefaultDecorated.call(DefaultDecorated.java:48) ~[selenium-support-4.0.0-beta-1.jar:?]
	at org.openqa.selenium.support.decorators.WebDriverDecorator.lambda$createProxy$0(WebDriverDecorator.java:287) ~[selenium-support-4.0.0-beta-1.jar:?]
	at com.sun.proxy.$Proxy30.executeScript(Unknown Source) ~[?:?]
	at com.frameworkium.lite.ui.pages.BasePage.executeJS(BasePage.java:167) ~[classes/:?]
```

**Comment by ham1** [comment]
See https://github.com/ham1/frameworkium-lite/tree/fix-select-for-sel-4-beta-2

**Comment by ham1** [comment]
Thanks for the comment, good idea, unfortunately the issue is actually with trying to replace `EventFiringWebDriver` with the `EventFiringDecorator`, it also prevents the JavaScriptExecutor from working too, or at least did, I need to pick this up again and test on the latest RC.
